# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   worker.event.matcher:
       class: AppBundle\Worker\Matcher

   redis.client:
       class: Redis
       calls:
            - [connect, ['127.0.0.1', '6379']]

   app.form.registration:
       class: AppBundle\Form\RegistrationType
       tags:
            - { name: form.type, alias: app_user_registration }
