# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   worker.event.consumer:
       class: AppBundle\Worker\EventConsumer
       arguments: ['@matcher.route', '@repository.user', '@doctrine.orm.entity_manager', '@event_dispatcher']

   matcher.route:
       class: AppBundle\Matcher\Route
       arguments: ['@repository.scenario', '@repository.user']

   redis.client:
       class: Redis
       calls:
            - [connect, ['127.0.0.1', '6379']]

   app.form.registration:
       class: AppBundle\Form\Type\RegistrationType
       tags:
           - { name: form.type, alias: app_user_registration }

   app.registration_success:
       class: AppBundle\EventListener\RegistrationSuccessEventListener
       arguments: [@router, @util.app_uid_generator]
       tags:
           - { name: kernel.event_subscriber }

   app.scenario_voter:
       class: AppBundle\Security\ScenarioVoter
       arguments: ['@security.access.decision_manager']
       tags:
           - { name: security.voter }
       # small performance boost
       public: false

   app.listener.route_matched:
       class: AppBundle\EventListener\RouteMatchedListener
       tags:
           - { name: kernel.event_subscriber }

   util.app_uid_generator:
       class: AppBundle\Util\AppUidGenerator
