# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   worker.event.consumer:
       class: AppBundle\Worker\EventConsumer

   matcher.route:
       class: AppBundle\Matcher\Route
       arguments: ['@repository.scenario']

   redis.client:
       class: Redis
       calls:
            - [connect, ['127.0.0.1', '6379']]

   app.form.registration:
       class: AppBundle\Form\Type\RegistrationType
       tags:
            - { name: form.type, alias: app_user_registration }

   app.registration_success:
       class: AppBundle\EventListener\RegistrationSuccessEventListener
       arguments: [@router]
       tags:
           - { name: kernel.event_subscriber }
